### ISSUE TITLE
Is it possible to specify modules from flutter?

### ISSUE THREAD

**Issue by barees63** [appspector/flutter-plugin#18]
Hi there, this is working great for me in general but I was wondering if there is a way, or if you have plans to support, selectively enabling collection modules as you can in the native SDKs?

**Comment by Dimdron** [comment]
Hi @barees63, we're glad to hear your feedback. We plan to implement this functionality in our next sprint. So, I guess it'll be available in about 2 months😉

**Comment by Dimdron** [comment]
Hey @barees63, we have good news for you :) Starting from 0.2.0 version you're able to specify monitors you want to use. 
You can find a sample here:
https://github.com/appspector/flutter-plugin#initialize-appspector-plugin
