### ISSUE TITLE
SQLite monitor don't work on Android

### ISSUE THREAD

**Issue by oaugustus** [appspector/flutter-plugin#25]
I have configured plugin like inscructions and it works fine on iOS, when I click on SQLite, shows all tables that I have on my app. But when I open on Android and click on SQLite, shows a message "The app doesn't have any databases".

Follow my configuration:

````
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  SharedPreferences session = await SharedPreferences.getInstance();

  DB db = DB();
  await db.initBd();
  runAppSpector();
  initializeDateFormatting('pt_BR', null)
      .then((_) => runApp(MyApp(session)));
}

void runAppSpector() {
  final config = Config()
    ..iosApiKey = "XXXXX"
    ..androidApiKey = "XXXX";

  config.monitors = [
    Monitors.http,
    Monitors.logs,
    Monitors.screenshot,
    Monitors.sqLite,
    Monitors.sharedPreferences
  ];

  AppSpectorPlugin.run(config);
}

**Comment by Dimdron** [comment]
Hi @oaugustus, could you show code with database initialization? I suppose it can be related to an unusual database path for Android.

**Comment by Dimdron** [comment]
Currently, I recommend using the next approach:
```dart
    var dbPath = await getDatabasesPath() + "/my_database_name.db";
    var theDb = await openDatabase(dbPath, version: 1, onCreate: _onCreate);
``` 
It's code from our [sample app](https://github.com/appspector/flutter-plugin/blob/master/example/lib/sqlite/storage.dart).

We're working on this issue in Android native SDK. So, I hope it'll be available for the flutter plugin in a couple of weeks.

**Comment by oaugustus** [comment]
Hi @Dimdron really, that was it. 
On my database initialization my code was like:

````
    Directory documentDir = await getApplicationDocumentsDirectory();

    String caminho = join(
        documentDir.path, "database.db"
    );
`````
I changed it to:

````
String path = await getDatabasesPath() + "/database.db";

````
And then works fine!

Thanks.
