### ISSUE TITLE
No network log when using 3rd party http client library

### ISSUE THREAD

**Issue by Stivfk** [appspector/flutter-plugin#27]
Hi AppSpector,

When I use Dio https://pub.dev/packages/dio, i'm not able to get any network log from Appspector app. 

If I don't use dio, i can confirm i get those network logs.

Regards,
Steeve

**Comment by sergeyzenchenko** [comment]
Hi Steeve. Let us looks into it. Thanks for feedback!

**Comment by Dimdron** [comment]
Hi @Stivfk, I've checked the sample app and it successfully works with DIO 3.0.9.
By default, DIO is based on the dart.io package and it provides capability with our plugin. Could you give more details about our environment/project/dependencies

**Comment by Stivfk** [comment]
thanks for quick feedback, let me do a sample app then i'll check on my app what's causing the issue.

I'll get back tomorrow

**Comment by codeets** [comment]
HI,  I am facing same problem. 

I am using  dio: ^4.0.1, there is no logs in network tab on console.

**Comment by Dimdron** [comment]
Hey, thanks for the info! We'll take a look soon.
