### ISSUE TITLE
FS Monitor breaking build in iOS 13.5

### ISSUE THREAD

**Issue by shaun0203** [appspector/flutter-plugin#29]
https://github.com/appspector/flutter-plugin/blob/0759aae9f94844fb327a94bea3983a64d49fc816/ios/Classes/AppSpectorPlugin.m#L179

**Comment by Dimdron** [comment]
Hi @shaun0203, I guess it's because you have not executed `pod update` command and, as a result, the plugin uses 1.2.x version instead of 1.3.x.
Could you open iOS module and run `pod update` command? It should solve your problem.

**Comment by shaun0203** [comment]
Yes, but shouldnt need  to do that, i have done a PR, it will update the pod when new sdk's are released. If you want that is.

**Comment by shaun0203** [comment]
Closing this issue, you can check PR
