### ISSUE TITLE
The non-abstract class 'HttpRequestWrapper' is missing implementations for these members:  - HttpClientRequest.abort

### ISSUE THREAD

**Issue by RusKryzhanovskiy** [appspector/flutter-plugin#31]
I found this one error for `appspector: ^0.3.0` during assembly of my project. 
```
../../flutter/.pub-cache/hosted/pub.dartlang.org/appspector-0.3.0/lib/src/http/request_wrapper.dart:8:7: Error: The non-abstract class 'HttpRequestWrapper' is missing implementations for these members:
 - HttpClientRequest.abort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class HttpRequestWrapper extends HttpClientRequest {
      ^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:2045:8: Context: 'HttpClientRequest.abort' is defined here.
  void abort([Object? exception, StackTrace? stackTrace]);
       ^^^^^


FAILURE: Build failed with an exception.

```
flutter --version
```
Flutter 1.21.0-10.0.pre.139 • channel master • https://github.com/flutter/flutter.git
Framework • revision a51dc3d913 (8 days ago) • 2020-08-18 02:51:02 -0400
Engine • revision 0b330467da
Tools • Dart 2.10.0 (build 2.10.0-38.0.dev)
```

**Comment by deszip** [comment]
Hi, thanks for reporting. We'll take a look.

**Comment by Dimdron** [comment]
Hey, @RusKryzhanovskiy I just tested it on the latest flutter version in the **stable** channel and it worked properly. 
I suggest you changing the flutter channel because the master one is the current tip-of-tree of the flutter dev branch.

**Comment by Dimdron** [comment]
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (13 дней назад) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

**Comment by sbosell** [comment]
The issue is on the beta channel which is what we are using as it supports web.

**Comment by rasmusir** [comment]
This issue is now in the stable channel.

Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (7 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0

**Comment by Dimdron** [comment]
Oh, thanks for the information. We're already in progress

**Comment by Dimdron** [comment]
Hey, could you try the 0.4.0 version, please?

**Comment by stephangopaul** [comment]
Version 0.4.0 fixes this issue. Thank you @Dimdron
