### ISSUE TITLE
On flutter I am not able to start sessions.

### ISSUE THREAD

**Issue by iavsm** [appspector/flutter-plugin#36]
AppSpector( 1355): Session start failed. UNKNOWN

I am continuously getting this error.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.0.1 20B50 darwin-x64, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.0)
[✓] Connected device (3 available)
    ! Error: iphone 12 pro max is busy: Copying cache files from device. Xcode will continue when iphone 12 pro max is finished. (code -10)
    ! Error: iPhone is busy: Waiting for Device. Xcode will continue when iPhone is finished. (code -10)

! Doctor found issues in 1 category.

**Comment by iavsm** [comment]
@Dimdron Please check

**Comment by Dimdron** [comment]
Yeah, I'm already looking at this. Have you been using our SDK previously in this project?

**Comment by iavsm** [comment]
No, I just started the first time in a flutter.

**Comment by iavsm** [comment]
I mean added the first time.

**Comment by iavsm** [comment]
![Screenshot 2021-02-06 at 6 28 07 PM](https://user-images.githubusercontent.com/6705574/107118795-10781900-68a9-11eb-96f4-114579b9e949.png)

**Comment by iavsm** [comment]
I am using the key that is provided below this line.

**Comment by iavsm** [comment]
` Future<void> runAppSpector(DataObservable<String> sessionObserver) async {
  final config = appSpector.Config()
    ..iosApiKey = "io"
    ..androidApiKey = "android_OWMz"
    ..monitors = [
      appSpector.Monitors.http,
      appSpector.Monitors.logs,
      appSpector.Monitors.fileSystem,
      appSpector.Monitors.screenshot,
      appSpector.Monitors.environment,
      appSpector.Monitors.location,
      appSpector.Monitors.performance,
      appSpector.Monitors.sqLite,
      appSpector.Monitors.sharedPreferences,
      appSpector.Monitors.analytics,
      appSpector.Monitors.notification,
      appSpector.Monitors.userDefaults,
      appSpector.Monitors.coreData
    ];

  appSpector.AppSpectorPlugin.run(config);

  appSpector.AppSpectorPlugin.shared()?.sessionUrlListener = (sessionUrl) => {
        Logger().d("Session URL $sessionUrl"),
        sessionObserver.setValue(sessionUrl)
      };
  await appSpector.AppSpectorPlugin.shared().start();
} `

**Comment by iavsm** [comment]
@Dimdron Let me know if you need more details.

**Comment by Dimdron** [comment]
> I am using the key that is provided below this line.
It's correct. 
> await appSpector.AppSpectorPlugin.shared().start();
This line is not necessary for starting the SDK. `AppSpectorPlugin.run(config);` is enough to start a session during launching the app.

**Comment by iavsm** [comment]
Okay let me remove and try again.

**Comment by iavsm** [comment]
Same error if i remove this - await appSpector.AppSpectorPlugin.shared().start();

**Comment by iavsm** [comment]
Previously I selected end-to-end encryption and now created a project without encryption and it starts collecting logs.
