### ISSUE TITLE
support flutter 2 + null safety

### ISSUE THREAD

**Issue by saharvx9** [appspector/flutter-plugin#42]
Pls support it :)

**Comment by deszip** [comment]
Hi @saharvx9 , what do you mean by null safety? 2.0 has some null handling changes? I've tested plugin today on 2.0 and it seems to work fine.

**Comment by saharvx9** [comment]
Pls read the docs how ti migrate flutter for null safety
https://dart.dev/null-safety
(As start update your pubspec sdk that will from 2.12)
