### ISSUE TITLE
Unable to build in Flutter after 3.0

### ISSUE THREAD

**Issue by Wu1z** [appspector/flutter-plugin#58]
When running my app on Flutter versions after 3.0, he is unable to build, and show this error:

: Error: The non-abstract class 'AppSpectorHttpClient' is missing implementations for these members

![image](https://user-images.githubusercontent.com/40008264/173353081-d2d8c790-cf1b-4302-ab7d-caf3cc2ab96a.png)

**Comment by deszip** [comment]
Hi @Wu1z , thanks for reporting this, we already have a pr (https://github.com/appspector/flutter-plugin/pull/57) opened with a fix. Im testing it right now. Hope we'll merge it today/tomorrow.

I'll ping you here once it will be ready.

**Comment by Wu1z** [comment]
> Hi @Wu1z , thanks for reporting this, we already have a pr (#57) opened with a fix. Im testing it right now. Hope we'll merge it today/tomorrow.
> 
> I'll ping you here once it will be ready.

Great!! I'm awaiting for it, thanks.
