### ISSUE TITLE
Issue receiving logs on Android 13 devices

### ISSUE THREAD

**Issue by kbessemer** [appspector/flutter-plugin#68]
Hello, I am currently in the trial, and attempting to receive debug logs for my Android app. I am not receiving logs for two Android 13 devices, these are the only Android 13 devices I have tried.

I have received logs successfully with the same app on Android 11, and 12.

The Android 13 devices:

Realme GT NEO 3T
realme RMX3371 | Android 13

Xiaomi 12 Pro
Xiaomi 2201122G | Android 13

The logs screen just says NO DATA

**Comment by Dimdron** [comment]
Hey, thanks for report. We're aware of it and fix is on the way.  🙌

**Comment by kbessemer** [comment]
Excellent, I really like what you guys have done with this plugin. Good to see it's being maintained.

**Comment by Dimdron** [comment]
It's fixed in the latest plugin version.
