### ISSUE TITLE
[iOS] Invalid privacy manifest

### ISSUE THREAD

**Issue by Dmitriy-Nezhidenko** [appspector/flutter-plugin#73]
I've got the following error when uploading the new release to AppStore.

> ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/AppSpectorSDK.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by devmobile-vulog** [comment]
Hello @Dmitriy-Nezhidenko 👋 
Were you able to fix this issue ?

**Comment by deszip** [comment]
Hi, can you pls try with the latest (1.4.12) version of the iOS SDK? We have a fix in this version.
You need to update plugin I guess.

**Comment by devmobile-vulog** [comment]
Roger that ! Will keep you posted, thanks 🙏

**Comment by devmobile-vulog** [comment]
It worked ! The app has been accepted on the App Store
Thanks Deszip 🙏

**Comment by deszip** [comment]
Great, glad to hear :)
Will close this, feel free to reopen if it does not work for you.
